# Generated by Django 2.2.6 on 2019-10-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsection',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/sport_app/templates/img'),
        ),
    ]
