# Generated by Django 3.0 on 2019-12-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsystem',
            name='level',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainingsystem',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
