# Generated by Django 2.2.6 on 2019-11-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportSectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=56)),
            ],
        ),
        migrations.AddField(
            model_name='trainingsystem',
            name='video',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sportsection',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/media/img'),
        ),
        migrations.CreateModel(
            name='OrderMemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_app.SportSection')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_app.Food')),
            ],
        ),
        migrations.AddField(
            model_name='sportsection',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport_app.SportSectionType'),
        ),
    ]
