# Generated by Django 2.2.6 on 2019-12-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0002_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='conn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_app.SportSection'),
        ),
    ]
