# Generated by Django 2.2.6 on 2019-12-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0002_auto_20191123_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsectiontype',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/media/img'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/media/img'),
        ),
    ]
