# Generated by Django 2.2.6 on 2019-11-04 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0002_sportsection_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('info', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='C:/Users/minot/PycharmProjects/sport/static/img')),
            ],
        ),
        migrations.AlterField(
            model_name='sportsection',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/static/img'),
        ),
        migrations.CreateModel(
            name='ReviewToCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_app.Coach')),
            ],
        ),
    ]
