# Generated by Django 2.1.13 on 2019-12-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0003_auto_20191208_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/media/img'),
        ),
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/media/img'),
        ),
        migrations.AlterField(
            model_name='sportsection',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/media/img'),
        ),
        migrations.AlterField(
            model_name='sportsectiontype',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/media/img'),
        ),
        migrations.AlterField(
            model_name='trainingsystem',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/media/img'),
        ),
    ]
