# Generated by Django 2.2.6 on 2019-12-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0003_auto_20191203_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='conn_id',
            field=models.IntegerField(),
        ),
    ]
