# Generated by Django 2.2.6 on 2019-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0004_auto_20191202_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsystem',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/media/img'),
        ),
    ]
