# Generated by Django 2.2.6 on 2019-11-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0004_auto_20191109_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='section_id',
            new_name='section',
        ),
    ]
