# Generated by Django 2.2.6 on 2019-12-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0005_trainingsystem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/Karim/PycharmProjects/sport/media/img'),
        ),
    ]
