# Generated by Django 2.2.6 on 2019-11-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0007_coach_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='section',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='section',
            new_name='section_id',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='location',
        ),
        migrations.AlterField(
            model_name='sportsection',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:/Users/minot/PycharmProjects/sport/static/img'),
        ),
        migrations.DeleteModel(
            name='ReviewToCoach',
        ),
    ]
